In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a2 =a[np.newaxis,:]
a2

array([[0, 1, 2, 3, 4, 5]])

In [5]:
a2.shape

(1, 6)

In [15]:
a = np.array(['1', 2, 3, 4, 5, 6])

In [16]:
a.dtype

dtype('<U11')

In [22]:
a.ndim

1

In [23]:
a.shape

(6,)

In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [25]:
a.dtype

dtype('int32')

In [26]:
a.ndim

2

In [27]:
a.shape

(3, 4)

In [28]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
a[0]

array([1, 2, 3, 4])

In [31]:
a[0,3]

4

In [33]:
a[:,3]

array([ 4,  8, 12])

In [39]:
np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [53]:
np.zeros((2,3),dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [44]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [51]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [54]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [69]:
np.sort(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [58]:
a = np.array([[1,4],[3,1]])
a

array([[1, 4],
       [3, 1]])

In [59]:
np.sort(a,axis=1)

array([[1, 4],
       [1, 3]])

In [60]:
np.sort(a,axis=0)

array([[1, 1],
       [3, 4]])

In [61]:
x = np.array([3, 1, 2])

In [62]:
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [63]:
np.argmax(x)

0

In [64]:
x = np.array([[0, 3], [2, 2]])

In [65]:
x

array([[0, 3],
       [2, 2]])

In [66]:
np.argsort(x, axis=-1)

array([[0, 1],
       [0, 1]], dtype=int64)

In [67]:
np.argsort(x, axis=1)

array([[0, 1],
       [0, 1]], dtype=int64)

In [68]:
 np.argsort(x, axis=0)

array([[0, 1],
       [1, 0]], dtype=int64)

In [77]:
a = np.array([[[1, 2, 3, 4]]])
b = np.array([[[5, 6, 7, 8]]])

In [84]:
np.concatenate((a,b),axis=0).shape

(2, 1, 4)

In [79]:
np.concatenate((a,b),axis=1)

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [80]:
np.concatenate((a,b),axis=2)

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [81]:
a.ndim

3

In [82]:
a.shape

(1, 1, 4)

In [83]:
a.size

4

In [85]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [86]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [88]:
a.reshape(2,2)

ValueError: cannot reshape array of size 6 into shape (2,2)

In [89]:
np.reshape(a,(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [90]:
a = np.array([1, 2, 3, 4, 5, 6])

In [91]:
a.shape

(6,)

In [93]:
a2 = a[np.newaxis,:]

In [94]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [95]:
a2.shape

(1, 6)

In [96]:
a3 = a[:,np.newaxis]

In [97]:
a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [98]:
a3.shape

(6, 1)

In [99]:
a

array([1, 2, 3, 4, 5, 6])

In [102]:
b = np.expand_dims(a,axis=1)

In [103]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [107]:
a4 = np.expand_dims(a3,axis=0)

In [106]:
a3.shape

(6, 1)

In [108]:
a4.shape

(1, 6, 1)

In [111]:
aa = a3.reshape((3,2))
aa

array([[1, 2],
       [3, 4],
       [5, 6]])

In [112]:
a4 = np.expand_dims(aa,axis=0)
a4.shape

(1, 3, 2)

In [113]:
a4 = np.expand_dims(aa,axis=1)
a4.shape

(3, 1, 2)

In [114]:
a4 = np.expand_dims(aa,axis=2)
a4.shape

(3, 2, 1)

In [115]:
a4 = np.expand_dims(aa,axis=3)
a4.shape

AxisError: axis 3 is out of bounds for array of dimension 3

In [116]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [117]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [118]:
a.ndim

2

In [120]:
a.shape

(3, 4)

In [122]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [123]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [125]:
a[(a>2) & (a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
a[(a>5)|(a==5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [127]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
b = np.nonzero(a<5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [130]:
list(zip(b[0],b[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [131]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
arr1 = a[3:8]

In [133]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
arr1

array([4, 5, 6, 7, 8])

In [135]:
arr1[0]=14

In [136]:
a

array([ 1,  2,  3, 14,  5,  6,  7,  8,  9, 10])

In [137]:
arr1

array([14,  5,  6,  7,  8])

In [142]:
a1 = np.array([[1, 1],
               [2, 2],[3,3]])
a2 = np.array([[3, 3],
               [4, 4]])

In [146]:
np.concatenate((a1,a2),axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [3, 3],
       [4, 4]])

In [147]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [3, 3],
       [4, 4]])

In [148]:
np.hstack((a1,a2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [149]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [150]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [151]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [152]:
data = np.array([1, 2])

In [153]:
ones = np.ones(2, dtype=int)

In [154]:
data

array([1, 2])

In [155]:
ones

array([1, 1])

In [156]:
data+ones

array([2, 3])

In [157]:
a = np.array([1, 2, 3, 4])

In [158]:
a.sum()

10

In [159]:
b = np.array([[1, 1], [2, 2]])

In [160]:
b.sum()

6

In [162]:
b

array([[1, 1],
       [2, 2]])

In [163]:
b.sum(1)

array([2, 4])

In [164]:
data = np.array([1.0, 2.0])

In [165]:
data

array([1., 2.])

In [166]:
data * 1.6

array([1.6, 3.2])

In [167]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

In [168]:
b = np.array([1.0, 2.0, 3.0])

In [169]:
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [170]:
c=np.array([8])

In [171]:
a*c

array([[  0.,   0.,   0.],
       [ 80.,  80.,  80.],
       [160., 160., 160.],
       [240., 240., 240.]])

In [196]:
rng = np.random.default_rng(1)

In [222]:
rng.random(3)

array([0.02449068, 0.67345989, 0.91908862])

In [226]:
rng.integers(1,5,endpoint=True)

5

In [227]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [231]:
np.unique(a,return_index=True,return_inverse=True,return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64),
 array([0, 0, 1, 2, 3, 4, 5, 6, 1, 2, 0, 3, 7, 8, 9], dtype=int64),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

In [233]:
data = np.arange(1,7).reshape(2,3)
data

array([[1, 2, 3],
       [4, 5, 6]])

In [234]:
data.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [235]:
data.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [238]:
arr = np.array([1, 2, 3, 4, 9, 6, 7, 8])

In [239]:
np.flip(arr)

array([8, 7, 6, 9, 4, 3, 2, 1])

In [240]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [241]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [244]:
np.flip(arr_2d,axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [245]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [246]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [247]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [248]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [251]:
x.reshape((1,-1))[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [253]:
x.reshape()

Docstring:
a.reshape(shape, order='C')

Returns an array containing the same data with a new shape.

Refer to `numpy.reshape` for full documentation.

See Also
--------
numpy.reshape : equivalent function

Notes
-----
Unlike the free function `numpy.reshape`, this method on `ndarray` allows
the elements of the shape parameter to be passed in as separate arguments.
For example, ``a.reshape(10, 11)`` is equivalent to
``a.reshape((10, 11))``.
Type:      builtin_function_or_method


In [254]:
def double(a):
    '''
    함수 사용법
    double(arr)
    '''
    return a*2

In [255]:
double?

Signature: double(a)
Docstring:
함수 사용법
double(arr)
File:      c:\users\user\appdata\local\temp\ipykernel_3980\3900343270.py
Type:      function


In [256]:
double??

Signature: double(a)
Source:   
def double(a):
    '''
    함수 사용법
    double(arr)
    '''
    return a*2
File:      c:\users\user\appdata\local\temp\ipykernel_3980\3900343270.py
Type:      function
