In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
import numpy as np

In [11]:
iris = load_iris()
dt_clf= DecisionTreeClassifier(random_state=156)
kfold = KFold(n_splits=5,shuffle=True)

In [12]:
cv_accuracy = []
n_iter = 0

for train_index,test_index in kfold.split(iris.data):
    # print(train_index)
    # print(test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    print(n_iter,accuracy)
    print(y_test)

1 0.9666666666666667
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2]
2 0.9333333333333333
[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2]
3 0.8666666666666667
[0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
4 0.9666666666666667
[0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2]
5 1.0
[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2]


In [13]:
np.round(np.mean(cv_accuracy),4)

0.9467

In [14]:
data = load_iris(as_frame=True)

In [16]:
data.target.value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [18]:
kfold = KFold(n_splits=3,shuffle=True)
cv_accuracy = []
n_iter = 0

for train_index,test_index in kfold.split(iris.data):
    # print(train_index)
    # print(test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    print(n_iter,accuracy)
    print(y_test)

1 0.9
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
2 0.98
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
3 0.92
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [31]:
kfold = StratifiedKFold(n_splits=3,shuffle=False)
cv_accuracy = []
n_iter = 0
iris = load_iris(as_frame=True)
for train_index,test_index in kfold.split(iris.data,iris.target):
    # print(train_index)
    # print(test_index)
    X_train,X_test = iris.data.iloc[train_index],iris.data.iloc[test_index]
    y_train,y_test = iris.target.iloc[train_index],iris.target.iloc[test_index]
    print('검증데이터 분포:',y_test.value_counts())
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    print(n_iter,accuracy)
    # print(y_test)

검증데이터 분포: 0    17
1    17
2    16
Name: target, dtype: int64
1 0.98
검증데이터 분포: 0    17
2    17
1    16
Name: target, dtype: int64
2 0.94
검증데이터 분포: 1    17
2    17
0    16
Name: target, dtype: int64
3 0.98


In [32]:
from sklearn.model_selection import cross_val_score

In [33]:
dt_clf= DecisionTreeClassifier(random_state=156)
iris = load_iris()
cross_val_score(dt_clf,iris.data,iris.target,cv=3)

array([0.98, 0.94, 0.98])

In [34]:
grid_param = {
    'max_depth':[1,2,3],
    'min_samples_split':[2,3],
}

In [42]:
from sklearn.model_selection import GridSearchCV,train_test_split
import pandas as pd

In [36]:
iris = load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.2,random_state=121)

In [38]:
dtree = DecisionTreeClassifier()
grid_dtree = GridSearchCV(dtree,grid_param,cv=3, refit=True)

In [39]:
grid_dtree.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [40]:
grid_dtree.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [44]:
df = pd.DataFrame( grid_dtree.cv_results_)

In [45]:
df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [46]:
df[[ 'params','mean_test_score','rank_test_score','split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.669935                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.669935                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.929590                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.919786                4   
4  {'max_depth': 3, 'min_samples_split': 2}         0.959893                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.959893                1   

   split0_test_score  split1_test_score  split2_test_score  
0           0.676471           0.666667           0.666667  
1           0.676471           0.666667           0.666667  
2           0.970588           0.939394           0.878788  
3           0.941176           0.939394           0.878788  
4           0.970588           0.939394           0.969697  
5           0.970588           0.939394           0.969697

In [48]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [49]:
grid_dtree.best_score_

0.9598930481283423

In [51]:
pred = grid_dtree.best_estimator_.predict(X_test)

In [52]:
accuracy_score(y_test,pred)

1.0